server:
  port: 8089

spring:
  application:
    name: dichvu-service
  datasource:
    #driverClassName: org.postgresql.Driver
    #url: jdbc:postgresql://tiny.db.elephantsql.com:5432/bzikodlt
    #username: bzikodlt
    #password: JnI5jiCYpFoE-8iO0eky_205dJTs3F5I
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/quanlyrapphim_dichvu
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
      #properties:
      #hibernate:
      #dialect: org.hibernate.dialect.PostgreSQLDialect
    #format_sql: true
  data:
    redis:
      host: redis-14439.c252.ap-southeast-1-1.ec2.redns.redis-cloud.com
      port: 14439
      password: vE33gQXSafSqeEzpR308UVMM04Z8jr08

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

application:
  config:
    progress-url: http://localhost:8060/api/progress


management:
  tracing:
    sampling:
      probability: 1.0

