server:
  port: 8082

spring:
  application:
    name: phongchieu-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/quanlyrapphim_phongchieu
    #url: jdbc:postgresql://tiny.db.elephantsql.com:5432/gybyqcln
    #username: gybyqcln
    #password: HjizMV3ck-8L-_Qh_dliXMzbSLGI5R42
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
      #properties:
      #hibernate:
      #dialect: org.hibernate.dialect.PostgreSQLDialect
    #format_sql: true
  data:
    redis:
      host: redis-14439.c252.ap-southeast-1-1.ec2.redns.redis-cloud.com
      port: 14439
      password: vE33gQXSafSqeEzpR308UVMM04Z8jr08

application:
  config:
    progress-url: http://localhost:8060/api/progress

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

