server:
  port: 8088

spring:
  application:
    name: ve-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/quanlyrapphim_ve
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: redis-14439.c252.ap-southeast-1-1.ec2.redns.redis-cloud.com
      port: 14439
      password: vE33gQXSafSqeEzpR308UVMM04Z8jr08

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

application:
  config:
    ghes-url: http://localhost:8060/api/ghes
    lichchieus-url: http://localhost:8060/api/lichchieus

management:
  tracing:
    sampling:
      probability: 1.0

